/* ===================================================================
 * SETSOUND.C  -  CASTALIA DOS Sound Configuration  (SETSOUND.EXE)
 * -------------------------------------------------------------------
 * Part of CASTALIA DOS.  Copyright (c) 2026 The Castalia DOS Project.
 * SPDX-License-Identifier: MIT
 *
 * Chooses a sound profile and writes C:\CASTALIA\CFG\SOUND.BAT - the
 * SET BLASTER / SET SOUND / SET MIDI lines that AUTOEXEC.BAT calls at
 * boot.  Keyboard-first, text mode, 386SX-friendly.
 *
 * SET BLASTER fields:  A=I/O port  I=IRQ  D=8-bit DMA  H=16-bit DMA
 *                      T=card type (1 SB1.5, 3 SB2.0, 4 SB Pro, 6 SB16)
 *
 * DOS cannot reliably auto-detect ISA sound cards, so this is a
 * choose-and-confirm tool with sensible defaults and manual override,
 * not a magic probe (see docs/SOUND.md).
 *
 * Build (Open Watcom):
 *   wcl -0 -bt=dos -ml -os setsound.c ..\common\ini.c ..\common\ui.c
 *
 * C89 only.  No dynamic allocation.
 * =================================================================== */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <conio.h>
#include "../common/UI.H"
#include "../common/SPK.H"
#include "../common/SAFEIO.H"

/* AUTOEXEC.BAT calls exactly this file; a SOUND.BAT anywhere else would
 * be written and then never run. */
#define SOUND_BAT "C:\\CASTALIA\\CFG\\SOUND.BAT"

/* A sound profile. */
typedef struct {
    char id[8];
    char label[26];
    int  has_blaster;   /* write a SET BLASTER line?        */
    int  type;          /* T value (0 = n/a)                */
    int  has_hdma;      /* include H (16-bit DMA)?          */
    char note[42];
} SND;

static SND snd[] = {
    { "NONE",  "No sound",            0, 0, 0, "Games run silently." },
    { "SPKR",  "PC Speaker",          0, 0, 0, "Built-in beeper; no card needed." },
    { "ADLIB", "AdLib (FM music)",    0, 0, 0, "OPL2 music; no digital sound." },
    { "SB",    "Sound Blaster 2.0",   1, 3, 0, "FM music + 8-bit digital." },
    { "SBPRO", "Sound Blaster Pro",   1, 4, 0, "Stereo FM + 8-bit digital." },
    { "SB16",  "Sound Blaster 16",    1, 6, 1, "16-bit digital + FM." }
};
#define NSND (int)(sizeof(snd) / sizeof(snd[0]))

/* Adjustable resource presets. */
static int port_opt[] = { 0x220, 0x240, 0x260 };
static int irq_opt[]  = { 5, 7, 10 };
static int dma_opt[]  = { 1, 3 };
static int hdma_opt[] = { 5, 6, 7 };
#define NPORT 3
#define NIRQ  3
#define NDMA  2
#define NHDMA 3

static int i_port = 0, i_irq = 0, i_dma = 0, i_hdma = 0;

/* Build the SET BLASTER value for the selected profile. */
static void build_blaster(int sel, char *out)
{
    SND *s = &snd[sel];
    if (!s->has_blaster) {
        out[0] = '\0';
        return;
    }
    sprintf(out, "A%X I%d D%d", port_opt[i_port], irq_opt[i_irq],
            dma_opt[i_dma]);
    if (s->has_hdma) {
        char tmp[16];
        sprintf(tmp, " H%d", hdma_opt[i_hdma]);
        strcat(out, tmp);
    }
    {
        char tmp[8];
        sprintf(tmp, " T%d", s->type);
        strcat(out, tmp);
    }
}

/* Write SOUND.BAT for the selected profile.  Returns 1 on success.
 *
 * The new file is written under a temporary name and swapped in only
 * when complete: a write that fails half-way leaves the previous
 * SOUND.BAT working instead of an empty one. */
static int write_sound(int sel)
{
    SND *s = &snd[sel];
    char bl[64], tmp[SIO_PATH];
    FILE *fp;

    if (sio_tmpname(SOUND_BAT, tmp) != SIO_OK)
        return 0;
    /* Binary mode: the lines carry their own CR LF, and text mode
     * would turn each "\r\n" into CR CR LF. */
    fp = fopen(tmp, "wb");
    if (fp == NULL)
        return 0;

    build_blaster(sel, bl);
    fprintf(fp, "@ECHO OFF\r\n");
    fprintf(fp, "REM Generated by CASTALIA SETSOUND.EXE - profile %s\r\n",
            s->id);
    if (s->has_blaster) {
        fprintf(fp, "SET BLASTER=%s\r\n", bl);
        fprintf(fp, "SET SOUND=C:\\CASTALIA\r\n");
        fprintf(fp, "SET MIDI=SYNTH:1 MAP:E\r\n");
    } else {
        fprintf(fp, "REM %s profile: no SET BLASTER needed.\r\n", s->id);
        fprintf(fp, "SET SOUND=C:\\CASTALIA\r\n");
    }
    if (sio_close(fp) != 0) {
        remove(tmp);
        return 0;
    }
    return sio_replace(tmp, SOUND_BAT) == SIO_OK;
}

/* --- UI ------------------------------------------------------------- */

#define LX 4
#define LY 3
#define LW 34

static void draw_screen(int sel)
{
    int i;
    char bl[64], line[72];
    unsigned char attr;

    ui_cls(A_DESKTOP);
    ui_fill(0, 0, SCR_W, 1, ' ', A_TITLE);
    ui_puts(2, 0, "CASTALIA DOS", A_TITLE);
    ui_puts(SCR_W - 14, 0, "Sound Setup", UI_ATTR(C_WHITE, C_BLUE));

    /* Profile list. */
    ui_box(LX, LY, LW, NSND + 2, A_FRAME);
    ui_puts(LX + 2, LY, " Sound profile ", A_TITLE);
    for (i = 0; i < NSND; i++) {
        attr = (i == sel) ? A_ITEMSEL : A_ITEM;
        ui_fill(LX + 1, LY + 1 + i, LW - 2, 1, ' ', attr);
        sprintf(line, " %-*.*s", LW - 4, LW - 4, snd[i].label);
        ui_puts(LX + 1, LY + 1 + i, line, attr);
    }

    /* Detail + resources. */
    ui_box(LX + LW + 2, LY, 36, NSND + 2, A_FRAME);
    ui_puts(LX + LW + 4, LY, " Details ", A_TITLE);
    ui_putlim(LX + LW + 4, LY + 1, snd[sel].note, 32, A_ITEM);

    build_blaster(sel, bl);
    if (snd[sel].has_blaster)
        sprintf(line, "SET BLASTER=%s", bl);
    else
        strcpy(line, "(no BLASTER variable)");
    ui_putlim(LX + LW + 4, LY + 3, line, 32, UI_ATTR(C_YELLOW, C_BLUE));

    if (snd[sel].has_blaster) {
        sprintf(line, "Port : %X   (P to change)", port_opt[i_port]);
        ui_puts(LX + LW + 4, LY + 5, line, A_ITEM);
        sprintf(line, "IRQ  : %d    (I to change)", irq_opt[i_irq]);
        ui_puts(LX + LW + 4, LY + 6, line, A_ITEM);
        sprintf(line, "DMA  : %d    (D to change)", dma_opt[i_dma]);
        ui_puts(LX + LW + 4, LY + 7, line, A_ITEM);
        if (snd[sel].has_hdma) {
            sprintf(line, "HDMA : %d    (H to change)", hdma_opt[i_hdma]);
            ui_puts(LX + LW + 4, LY + 8, line, A_ITEM);
        }
    } else {
        ui_puts(LX + LW + 4, LY + 5,
                "No port/IRQ/DMA for this profile.", A_HINT);
    }

    ui_fill(0, SCR_H - 1, SCR_W, 1, ' ', A_STATUS);
    ui_puts(2, SCR_H - 1,
        " Up/Down Select  P I D H Adjust  T Test  Enter Save  Esc Quit",
        A_STATUS);
}

static void msgbox(const char *l1, const char *l2)
{
    int w = 54, h = 8, x = (SCR_W - w) / 2, y = (SCR_H - h) / 2;
    ui_fill(x, y, w, h, ' ', A_PANEL);
    ui_box(x, y, w, h, A_PANEL);
    ui_fill(x + 1, y, w - 2, 1, ' ', A_PANELHDR);
    ui_puts(x + 2, y, " Sound Setup ", A_PANELHDR);
    if (l1) ui_putlim(x + 3, y + 2, l1, w - 6, A_PANEL);
    if (l2) ui_putlim(x + 3, y + 4, l2, w - 6, A_PANEL);
    ui_getkey();
}

/* Play a short rising chime as an "is it wired?" check.  It always uses the
 * PC speaker - the one output DOS can safely drive on any machine - so it
 * confirms the beeper and timer; real card audio is proven by a game. */
static void test_sound(void)
{
    ui_puts(LX + LW + 4, LY + 10, "\x0E Testing PC speaker...",
            UI_ATTR(C_YELLOW, C_BLUE));
    spk_tone(880, 3);       /* A5  */
    spk_tone(1109, 3);      /* C#6 */
    spk_tone(1319, 5);      /* E6  */
}

int main(void)
{
    int sel = 4;                 /* default to SB Pro */
    int key;

    ui_init();
    for (;;) {
        draw_screen(sel);
        key = ui_getkey();
        if (key == KEY_ESC)
            break;
        else if (key == KEY_UP)
            sel = (sel > 0) ? sel - 1 : NSND - 1;
        else if (key == KEY_DOWN)
            sel = (sel < NSND - 1) ? sel + 1 : 0;
        else if (key == 'p' || key == 'P')
            i_port = (i_port + 1) % NPORT;
        else if (key == 'i' || key == 'I')
            i_irq = (i_irq + 1) % NIRQ;
        else if (key == 'd' || key == 'D')
            i_dma = (i_dma + 1) % NDMA;
        else if (key == 'h' || key == 'H')
            i_hdma = (i_hdma + 1) % NHDMA;
        else if (key == 't' || key == 'T')
            test_sound();
        else if (key == KEY_ENTER) {
            ui_crit_take();         /* report only this write's error */
            if (write_sound(sel)) {
                char m[80];
                sprintf(m, "Saved %s (profile %s).", SOUND_BAT, snd[sel].id);
                msgbox(m, "Reboot or re-run AUTOEXEC for it to take effect.");
            } else {
                int crit = ui_crit_take();
                msgbox("Could not write SOUND.BAT; nothing changed.",
                       crit >= 0 ? ui_crit_text(crit) :
                       "Check that C:\\CASTALIA\\CFG exists.");
            }
        }
    }
    ui_cls(UI_ATTR(C_LGRAY, C_BLACK));
    ui_done();
    return 0;
}
